steps:
  - name: 'gcr.io/cloud-builders/yarn'
    args: ['install']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo 'NEXT_PUBLIC_FRONT_URL="${_NEXT_PUBLIC_FRONT_URL}"' >> .env
        echo 'NEXT_PUBLIC_GOOGLE_ANALYTICS_ID="${_NEXT_PUBLIC_GOOGLE_ANALYTICS_ID}"' >> .env
        echo 'NEXT_PUBLIC_FIREBASE_API_KEY="${_NEXT_PUBLIC_FIREBASE_API_KEY}"' >> .env
        echo 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}"' >> .env
        echo 'NEXT_PUBLIC_FIREBASE_PROJECT_ID="${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}"' >> .env
        echo 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}"' >> .env
        echo 'NEXT_PUBLIC_FIREBASE_MESSEGING_SENDER_ID="${_NEXT_PUBLIC_FIREBASE_MESSEGING_SENDER_ID}"' >> .env
        echo 'NEXT_PUBLIC_FIREBASE_APP_ID="${_NEXT_PUBLIC_FIREBASE_APP_ID}"' >> .env
        echo 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID="${_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}"' >> .env
        echo 'FIREBASE_ADMIN_CLIENT_EMAIL="${_FIREBASE_ADMIN_CLIENT_EMAIL}"' >> .env
        echo 'FIREBASE_ADMIN_PRIVATE_KEY="${_FIREBASE_ADMIN_PRIVATE_KEY}"' >> .env
        cat .env

  - name: 'gcr.io/cloud-builders/yarn'
    args: ['build']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      ['app', 'deploy', '--appyaml=./deploy/frontend.yaml', '--stop-previous-version', '--quiet']

timeout: 1800s
