name: PR Workflow

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  PR:
    if: ${{ !contains(toJson(github.event.pull_request.labels), '[Skip] CI') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Enable node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn install

      - name: Lint types and code
        run: yarn lint

      - name: Set up firebase config
        run: echo '${{ secrets.FIREBASE_CONFIG }}' > .env

      - name: Build packages
        run: yarn build

      - name: Run tests
        run: yarn test
